use poetry in CI (#52)

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -1,39 +1,99 @@
 name: Run pytest
 
-on: [push, pull_request]
+on:
+  push:
+    branches-ignore:
+      - main
+  pull_request:
+    branches:
+      - main
+
+env:
+  POSTGRES_DB: tsdb
+  POSTGRES_USER: pguser
+  POSTGRES_PASSWORD: pgpass
+  POSTGRES_PORT: 5432
+  POSTGRES_HOST: localhost
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ["3.9", "3.10"]
+        python-version: ["3.9", "3.10", "3.11"]
+
+
+    services:
+      postgres:
+        image: timescale/timescaledb:latest-pg15
+        env:
+          POSTGRES_DB: ${{ env.POSTGRES_DB }}
+          POSTGRES_USER: ${{ env.POSTGRES_USER }}
+          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
+          POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
+          POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
+        ports:
+          - 5432:5432
+        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
+
+      - name: Create TABLE_NAME variable
+        run: |
+          TABLE_NAME="conditions_ci_${{ matrix.python-version }}"
+          TABLE_NAME=${TABLE_NAME//./_}
+          echo "Table name is $TABLE_NAME"
+          echo "TABLE_NAME=$TABLE_NAME" >> $GITHUB_ENV
+
+      - name: Execute DB setup script
+        continue-on-error: false # stop the workflow if this step fails
+        env:
+          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
+          TABLE_NAME: ${{ env.TABLE_NAME }}
+        run: |
+          set -e  # stop the shell script if any command fails
+          psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -f db/create_table_and_roles.sql  -v table_name=$TABLE_NAME
+
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
+      # - name: Install OS dependencies
+      #   run: |
+      #     DEBIAN_FRONTEND=noninteractive apt update
+      #     DEBIAN_FRONTEND=noninteractive apt install curl
+      - uses: snok/install-poetry@v1
+        with:
+          version: 1.6.1 # pin the version as they keep changing their APIs
+          virtualenvs-create: false
+          virtualenvs-in-project: false
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip
-          pip install -r test-requirements.txt
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          python -m venv venv
+          . venv/bin/activate
+          poetry install --with test --without dev  --no-interaction --no-root --sync
+          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
+          python  -c "import os; print(os.environ['VIRTUAL_ENV'])"
+
       - name: Lint with flake8
         run: |
+          . venv/bin/activate
           # stop the build if there are Python syntax errors or undefined names
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
           # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+
       - name: Test with pytest
         env:
-          TIMESCALE_CONNECTION_STRING: ${{ secrets.TIMESCALE_CONNECTION_STRING }}
+          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
+          TABLE_NAME: ${{ env.TABLE_NAME }}
+          POSTGRES_USER: ${{ format('{0}_writer_user', env.TABLE_NAME) }}
+          POSTGRES_PASSWORD: ${{ format('{0}_writer_user', env.TABLE_NAME) }}
         run: |
-          pytest
+          . venv/bin/activate
+          pytest --cov-report=xml
 
-          
       - name: Coverage comment
         id: coverage_comment
         uses: py-cov-action/python-coverage-comment-action@v3
@@ -49,4 +109,3 @@ jobs:
           name: python-coverage-comment-action
           # If you use a different name, update COMMENT_FILENAME accordingly
           path: python-coverage-comment-action.txt
-
